hw5
AlenaMikalaeynaLisava/TMSA pull request #5
Opened 2022-10-18 05:43 UTC by AlenaMikalaeynaLisava

2022-10-20 13:55 UTC, oromis1508 commented on hw5/task1Adv.ts
> +    else return false
Можно просто вернуть значение выражения, т.е. return (a+b>c)&&(a+c>b)&&(b+c>a).
Например есть функция:
>function getBool(isTrue: boolean) {
if(isTrue === true) return true //или просто if(isTrue)
else if(isTrue === false) return false //т.к. boolean это true или false, то альтернатива это просто else
}

Здесь видно, что если значение true или false, то мы возвращаем это значение. Поэтому здесь нет смысла от if, то же самое в случае с логическим выражением (a+b>c)&&(a+c>b)&&(b+c>a), оно всегда вернёт true или false, что нам и нужно

2022-10-20 14:09 UTC, oromis1508 commented on hw5/task2.ts
> +    return credit - money;
здесь не совсем правильно используется переменная money, т.к. если вызвать getOverpayment просто с числом, то будет использована та же переменная с 100, правильнее сделать money без инициализации и потом проверить в самой функции:
>if(!money) money = credit;

2022-10-20 14:10 UTC, oromis1508 commented on hw5/task2.ts
> +    credit = credit + credit*percentPerYear/100;
здесь не совсем правильная формула, сумма наоборот должна уменьшаться, т.к. кредит постепенно выплачивается

2022-10-20 14:18 UTC, alexch0110 commented on hw5/task2Adv.ts
> + if(n>1 && m>1) return (n-1)+(m-1);
не совсем правильно, при 3х4 должно быть 11:
1. ломаем на 3 штуки 1х4 - это 2 раза
2. каждую 1х4 нужно поломать еще 3 раза 
3 * 3 + 2 = 11
вариантов решения несколько, самый простой m*n - 1, второй вариант - найти min и max и формулой max * (min - 1) + max - 1

2022-10-20 14:21 UTC, oromis1508 commented on hw5/task4.ts
> +    const arr = ("" + num).split("");
split("") не имеет смысла, т.к. к символам в строке тоже можно обращаться по индексу

2022-10-20 14:25 UTC, oromis1508 commented on hw5/task5.ts
> +    }else sum = a;
else if(b<a) можно поменять на else
else sum = a; убрать
В случае если a === b, то цикл в else выполнится 1 раз и в сумме будет только 1 число

2022-10-20 14:27 UTC, alexch0110 commented on hw5/task6.ts
> +    boolValue === true?foo():boo();
просто boolValue ? foo():boo();

2022-10-20 14:29 UTC, oromis1508 requested changes
Выполнено отлично, замечания небольшие, но есть

2022-10-20 15:32 UTC, AlenaMikalaeynaLisava commented
Переделала там немного task2 но что-то не уверена(

2022-10-21 13:10 UTC, oromis1508 approved these changes
Огонь, теперь всё хорошо

2022-10-21 14:41 UTC, merged